myapp/config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  get 'app_dashboard/index'
  get 'app_dashboard/data'
  get 'app_dashboard/stream_csv'
  post 'app_dashboard/process_data'
  
  root 'home#index'
  
  devise_for :users

  mount Sidekiq::Web => "/sidekiq"
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

myapp/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

myapp/app/models/product.rb
class Product < ApplicationRecord
end

myapp/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

myapp/app/controllers/app_dashboard_controller.rb
class AppDashboardController < ApplicationController
  def index
    ActionCable.server.broadcast("csv_#{current_user.id}", { body: "Dashboard index" })    
  end

  def data
    products_db = Product.all
  end

  def process_data
    ActionCable.server.broadcast("csv_#{current_user.id}", { body: "Before Process data enqueue" })
    CsvExportJob.perform_later(current_user.id, Product.all.to_a)
    ActionCable.server.broadcast("csv_#{current_user.id}", { body: "Process Data enqueue" })
    #redirect_to({ action: "data" }, notice: "Export processing on data")
    render json: "ok"
  end

  def stream_csv
    send_file File.join(Rails.root, "tmp", Rails.env, "toto#{current_user.id}.csv")
  end
end

myapp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
end

myapp/app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!, :only => [:index]
  
  def index
  end
end

myapp/app/helpers/app_dashboard_helper.rb
module AppDashboardHelper
end

myapp/app/helpers/application_helper.rb
module ApplicationHelper
end

myapp/app/helpers/home_helper.rb
module HomeHelper
end

myapp/app/views/app_dashboard/data.html.erb
<h1>Data</h1>
<div>
    <p>You are connected with <%= current_user.email %> id : <%= current_user.id %></p>
	<%= link_to app_dashboard_process_data_path, method: :post, remote: true, class: 'btn btn-primary' do %>Process export<% end %>
	<%= link_to destroy_user_session_path, method: :delete do %>Log out<% end %>
</div>

myapp/app/views/app_dashboard/index.html.erb
<h1>Welcome Dashboard</h1>
<% if current_user.nil? %>
	<%= link_to new_user_session_path, class: 'btn btn-primary' do %>Sign in<% end %>
<% else %>
    <p>You are connected with <%= current_user.email %></p>
	<%= link_to app_dashboard_data_path, class: 'btn btn-primary' do %>Go to Export CSV<% end %>
	<%= link_to destroy_user_session_path, method: :delete do %>Log out<% end %>
<% end %>

myapp/app/views/home/index.html.erb
<h1>Welcome Home</h1>
<% if current_user.nil? %>
	<%= link_to new_user_session_path, class: 'btn btn-primary' do %>Sign in<% end %>
<% else %>
    <p>You are connected with <%= current_user.email %></p>
	<%= link_to app_dashboard_index_path, class: 'btn btn-primary' do %>Go to App<% end %>
	<%= link_to destroy_user_session_path, method: :delete do %>Log out<% end %>
<% end %>

myapp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <%= link_to "Home", root_path, class: "nav-link" %>
            </li>            
            <%# <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Dropdown
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li><a class="dropdown-item" href="#">Action</a></li>
                <li><a class="dropdown-item" href="#">Another action</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="#">Something else here</a></li>
              </ul>
            </li>
            <li class="nav-item">
              <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
            </li> %>
          </ul>
          <ul class="navbar-nav me-2 mb-2 mb-lg-0 d-flex">
            <li class="nav-item">
              <a class="nav-link d-flex" href="#">Link</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <div class="container">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
      <div> 
        <h3>Message broadcast</h3>
        <div id="message"></div>
      </div>
    </div>
  </body>
</html>